
title: CityJSON
description: JSON-based encoding for 3D city models
theme: just-the-docs

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.cityjson.org" # the base hostname & protocol for your site, e.g. http://example.com
# url: https://just-the-docs.github.io

lastversion: "2.0.0"


future:    true

permalink: pretty
exclude: ["node_modules/", "*.gemspec", "*.gem", "Gemfile", "Gemfile.lock", "package.json", "package-lock.json",  "script/", "LICENSE.txt", "lib/", "bin/", "README.md", "Rakefile"]

plugins:
  - jekyll-seo-tag
  
# Enable or disable the site search
search_enabled: true

# Aux links for the upper right navigation
# aux_links:
  # "GitHub repository":
    # - "//github.com/tudelft3d/cityjson"

callouts:
  warning:
    title: Warning
    color: red

# heading_anchors: true

kramdown:
  hard_wrap:      false
  toc_levels:     2..4

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "(edit this page on GitHub)"
gh_edit_repository: "https://github.com/cityjson/website" # the github URL for your repo
gh_edit_branch: "master" # the branch that your docs is served from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
